//------------------------------------------------------------------------------
// <auto-generated>
//     This code simulates generated code in a file without a special pattern in the file name.
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable All

namespace CSharp70.UseExpressionBodyForConstructors
{
    public class GeneratedClassWithEmptyConstructors
    {
        static GeneratedClassWithEmptyConstructors()
        {
        }
        public GeneratedClassWithEmptyConstructors()
        {
        }
        public GeneratedClassWithEmptyConstructors(int i)
        {
        }
        public GeneratedClassWithEmptyConstructors(int i, string s)
        {
        }
        public GeneratedClassWithEmptyConstructors(int i, string s, double d) : this(i, s)
        {
        }
        public GeneratedClassWithEmptyConstructors(int i, string s, double d, bool b) : this(i, s, d)
        {
        }
    }
}